In [18]:
import pandas as pd
import requests

In [19]:
# get API key by login on TMDB site
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=17bd2d67dc3c42c0db9bf2a0c0d85dc6&language=en-US&page=1')

In [20]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 91.156,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 17133},
  {'adult': False,
   'backdrop_path': '/wPU78OPN4BYEgWYdXyg0phMee64.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 82.261,
   'poster_path': '/hBcY0fE9pfXzvVaY4GKarweriG2.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 22912},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 58.067,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.6,
   'vote_count': 10388},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 83.292,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.6,
   'vote_count': 13580},
  {'adult': False,
   'backdrop_path': '/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 34.606,
   'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
   'release_date': '1995-10-19',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.6,
   'vote_count': 3989},
  {'adult': False,
   'backdrop_path': '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 92.606,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 13697},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 34.929,
   'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 6892},
  {'adult': False,
   'backdrop_path': '/rl7Jw8PjhSIjArOlDNv0JQPL1ZV.jpg',
   'genre_ids': [10749, 18],
   'id': 851644,
   'original_language': 'ko',
   'original_title': '20세기 소녀',
   'overview': "Yeon-du asks her best friend Bora to collect all the information she can about Baek Hyun-jin while she is away in the U.S. for heart surgery. Bora decides to get close to Baek's best friend, Pung Woon-ho first. However, Bora's clumsy plan unfolds in an unexpected direction. In 1999, a year before the new century, Bora, who turns seventeen, falls into the fever of first love.",
   'popularity': 155.068,
   'poster_path': '/od22ftNnyag0TTxcnJhlsu3aLoU.jpg',
   'release_date': '2022-10-06',
   'title': '20th Century Girl',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 336},
  {'adult': False,
   'backdrop_path': '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
   'genre_ids': [10749, 16, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 89.208,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 9327},
  {'adult': False,
   'backdrop_path': '/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg',
   'genre_ids': [10749, 16],
   'id': 372754,
   'original_language': 'ja',
   'original_title': '同級生',
   'overview': 'Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.',
   'popularity': 13.187,
   'poster_path': '/cIfRCA5wEvj9tApca4UDUagQEiM.jpg',
   'release_date': '2016-02-20',
   'title': 'Dou kyu sei – Classmates',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 279},
  {'adult': False,
   'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 77.677,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 14915},
  {'adult': False,
   'backdrop_path': '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 87.016,
   'poster_path': '/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 14765},
  {'adult': False,
   'backdrop_path': '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 76.638,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-14',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 28804},
  {'adult': False,
   'backdrop_path': '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
   'genre_ids': [10749],
   'id': 696374,
   'original_language': 'en',
   'original_title': "Gabriel's Inferno",
   'overview': "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
   'popularity': 12.694,
   'poster_path': '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
   'release_date': '2020-05-29',
   'title': "Gabriel's Inferno",
   'video': False,
   'vote_average': 8.5,
   'vote_count': 2309},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 73.588,
   'poster_path': '/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 24282},
  {'adult': False,
   'backdrop_path': '/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg',
   'genre_ids': [10749],
   'id': 724089,
   'original_language': 'en',
   'original_title': "Gabriel's Inferno: Part II",
   'overview': "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
   'popularity': 14.065,
   'poster_path': '/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg',
   'release_date': '2020-07-31',
   'title': "Gabriel's Inferno: Part II",
   'video': False,
   'vote_average': 8.5,
   'vote_count': 1449},
  {'adult': False,
   'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 62.003,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-23',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 7065},
  {'adult': False,
   'backdrop_path': '/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 79.492,
   'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 23793},
  {'adult': False,
   'backdrop_path': '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
   'popularity': 108.191,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-01',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 20760},
  {'adult': False,
   'backdrop_path': '/sw7mordbZxgITU877yTpZCud90M.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 46.669,
   'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 10780}],
 'total_pages': 531,
 'total_results': 10613}

In [21]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 91.156,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'title': 'The Godfather',
  'video': False,
  'vote_average': 8.7,
  'vote_count': 17133},
 {'adult': False,
  'backdrop_path': '/wPU78OPN4BYEgWYdXyg0phMee64.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 82.261,
  'poster_path': '/hBcY0fE9pfXzvVaY4GKarweriG2.jpg',
  'release_date': '1994-09-23',
  'title': 'The Shawshank Redemption',
  'video': False,
  'vote_average': 8.7,
  'vote_count': 22912},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 58.067,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'title': 'The Godfather Part II',
  'video': False,
  'vote_average': 8.6,
  'vote_count': 10388},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 83.292,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'title': "Schindler's List",
  'video': False,
  'vote_average': 8.6,
  'vote_count': 13580},
 {'adult': False,
  'backdrop_path': '/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 34.606,
  'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
  'release_date': '1995-10-19',
  'title': 'Dilwale Dulhania Le Jayenge',
  'video': False,
  'vote_average': 8.6,
  'vote_count': 3989},
 {'adult': False,
  'backdrop_path': '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 92.606,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'title': 'Spirited Away',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 13697},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 34.929,
  'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
  'release_date': '1957-04-10',
  'title': '12 Angry Men',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 6892},
 {'adult': False,
  'backdrop_path': '/rl7Jw8PjhSIjArOlDNv0JQPL1ZV.jpg',
  'genre_ids': [10749, 18],
  'id': 851644,
  'original_language': 'ko',
  'original_title': '20세기 소녀',
  'overview': "Yeon-du asks her best friend Bora to collect all the information she can about Baek Hyun-jin while she is away in the U.S. for heart surgery. Bora decides to get close to Baek's best friend, Pung Woon-ho first. However, Bora's clumsy plan unfolds in an unexpected direction. In 1999, a year before the new century, Bora, who turns seventeen, falls into the fever of first love.",
  'popularity': 155.068,
  'poster_path': '/od22ftNnyag0TTxcnJhlsu3aLoU.jpg',
  'release_date': '2022-10-06',
  'title': '20th Century Girl',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 336},
 {'adult': False,
  'backdrop_path': '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
  'genre_ids': [10749, 16, 18],
  'id': 372058,
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 89.208,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-08-26',
  'title': 'Your Name.',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 9327},
 {'adult': False,
  'backdrop_path': '/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg',
  'genre_ids': [10749, 16],
  'id': 372754,
  'original_language': 'ja',
  'original_title': '同級生',
  'overview': 'Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.',
  'popularity': 13.187,
  'poster_path': '/cIfRCA5wEvj9tApca4UDUagQEiM.jpg',
  'release_date': '2016-02-20',
  'title': 'Dou kyu sei – Classmates',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 279},
 {'adult': False,
  'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 77.677,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'title': 'Parasite',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 14915},
 {'adult': False,
  'backdrop_path': '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 87.016,
  'poster_path': '/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
  'release_date': '1999-12-10',
  'title': 'The Green Mile',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 14765},
 {'adult': False,
  'backdrop_path': '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
  'genre_ids': [18, 28, 80, 53],
  'id': 155,
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 76.638,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-14',
  'title': 'The Dark Knight',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 28804},
 {'adult': False,
  'backdrop_path': '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
  'genre_ids': [10749],
  'id': 696374,
  'original_language': 'en',
  'original_title': "Gabriel's Inferno",
  'overview': "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
  'popularity': 12.694,
  'poster_path': '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
  'release_date': '2020-05-29',
  'title': "Gabriel's Inferno",
  'video': False,
  'vote_average': 8.5,
  'vote_count': 2309},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80],
  'id': 680,
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 73.588,
  'poster_path': '/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg',
  'release_date': '1994-09-10',
  'title': 'Pulp Fiction',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 24282},
 {'adult': False,
  'backdrop_path': '/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg',
  'genre_ids': [10749],
  'id': 724089,
  'original_language': 'en',
  'original_title': "Gabriel's Inferno: Part II",
  'overview': "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
  'popularity': 14.065,
  'poster_path': '/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg',
  'release_date': '2020-07-31',
  'title': "Gabriel's Inferno: Part II",
  'video': False,
  'vote_average': 8.5,
  'vote_count': 1449},
 {'adult': False,
  'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
  'genre_ids': [37],
  'id': 429,
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 62.003,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-23',
  'title': 'The Good, the Bad and the Ugly',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 7065},
 {'adult': False,
  'backdrop_path': '/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 13,
  'original_language': 'en',
  'original_title': 'Forrest Gump',
  'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
  'popularity': 79.492,
  'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
  'release_date': '1994-06-23',
  'title': 'Forrest Gump',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 23793},
 {'adult': False,
  'backdrop_path': '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
  'popularity': 108.191,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-01',
  'title': 'The Lord of the Rings: The Return of the King',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 20760},
 {'adult': False,
  'backdrop_path': '/sw7mordbZxgITU877yTpZCud90M.jpg',
  'genre_ids': [18, 80],
  'id': 769,
  'original_language': 'en',
  'original_title': 'GoodFellas',
  'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
  'popularity': 46.669,
  'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
  'release_date': '1990-09-12',
  'title': 'GoodFellas',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 10780}]

In [22]:
movies_data = pd.DataFrame(response.json()['results'])

In [23]:
movies_data

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",91.156,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.7,17133
1,False,/wPU78OPN4BYEgWYdXyg0phMee64.jpg,"[18, 80]",278,en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,82.261,/hBcY0fE9pfXzvVaY4GKarweriG2.jpg,1994-09-23,The Shawshank Redemption,False,8.7,22912
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,58.067,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.6,10388
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,83.292,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.6,13580
4,False,/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",34.606,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-19,Dilwale Dulhania Le Jayenge,False,8.6,3989
5,False,/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",92.606,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.5,13697
6,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,34.929,/ppd84D2i9W8jXmsyInGyihiSyqz.jpg,1957-04-10,12 Angry Men,False,8.5,6892
7,False,/rl7Jw8PjhSIjArOlDNv0JQPL1ZV.jpg,"[10749, 18]",851644,ko,20세기 소녀,Yeon-du asks her best friend Bora to collect a...,155.068,/od22ftNnyag0TTxcnJhlsu3aLoU.jpg,2022-10-06,20th Century Girl,False,8.5,336
8,False,/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg,"[10749, 16, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,89.208,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.5,9327
9,False,/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg,"[10749, 16]",372754,ja,同級生,"Rihito Sajo, an honor student with a perfect s...",13.187,/cIfRCA5wEvj9tApca4UDUagQEiM.jpg,2016-02-20,Dou kyu sei – Classmates,False,8.5,279
10,False,/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",77.677,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.5,14915
11,False,/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,87.016,/velWPhVMQeQKcxggNEU8YmIo52R.jpg,1999-12-10,The Green Mile,False,8.5,14765
12,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,76.638,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-14,The Dark Knight,False,8.5,28804
13,False,/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg,[10749],696374,en,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,12.694,/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg,2020-05-29,Gabriel's Inferno,False,8.5,2309
14,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",73.588,/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg,1994-09-10,Pulp Fiction,False,8.5,24282
15,False,/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg,[10749],724089,en,Gabriel's Inferno: Part II,Professor Gabriel Emerson finally learns the t...,14.065,/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg,2020-07-31,Gabriel's Inferno: Part II,False,8.5,1449
16,False,/x4biAVdPVCghBlsVIzB6NmbghIz.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,62.003,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-23,"The Good, the Bad and the Ugly",False,8.5,7065
17,False,/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,79.492,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.5,23793
18,False,/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,108.191,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-01,The Lord of the Rings: The Return of the King,False,8.5,20760
19,False,/sw7mordbZxgITU877yTpZCud90M.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",46.669,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.5,10780

In [24]:
top_movies = movies_data[['title', 'overview', 'release_date', 'genre_ids', 'vote_average']]

In [25]:
top_movies

,title,overview,release_date,genre_ids,vote_average
0,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,"[18, 80]",8.7
1,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,"[18, 80]",8.7
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,"[18, 80]",8.6
3,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,"[18, 36, 10752]",8.6
4,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-19,"[35, 18, 10749]",8.6
5,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,"[16, 10751, 14]",8.5
6,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,[18],8.5
7,20th Century Girl,Yeon-du asks her best friend Bora to collect a...,2022-10-06,"[10749, 18]",8.5
8,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,"[10749, 16, 18]",8.5
9,Dou kyu sei – Classmates,"Rihito Sajo, an honor student with a perfect s...",2016-02-20,"[10749, 16]",8.5
10,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,"[35, 53, 18]",8.5
11,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,"[14, 18, 80]",8.5
12,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-14,"[18, 28, 80, 53]",8.5
13,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,2020-05-29,[10749],8.5
14,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,"[53, 80]",8.5
15,Gabriel's Inferno: Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,[10749],8.5
16,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,[37],8.5
17,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,"[35, 18, 10749]",8.5
18,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,2003-12-01,"[12, 14, 28]",8.5
19,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,"[18, 80]",8.5

In [26]:
all_movies = pd.DataFrame()

In [27]:
for i in range(1,500):
  requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=17bd2d67dc3c42c0db9bf2a0c0d85dc6&language=en-US&page={}'.format(i))
  temp_df = pd.DataFrame(response.json()['results'])[['title', 'overview', 'release_date', 'genre_ids', 'vote_average']]
  all_movies = all_movies.append(temp_df, ignore_index=True)

In [28]:
all_movies

,title,overview,release_date,genre_ids,vote_average
0,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,"[18, 80]",8.7
1,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,"[18, 80]",8.7
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,"[18, 80]",8.6
3,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,"[18, 36, 10752]",8.6
4,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-19,"[35, 18, 10749]",8.6
...,...,...,...,...,...
9975,Gabriel's Inferno: Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,[10749],8.5
9976,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,[37],8.5
9977,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,"[35, 18, 10749]",8.5
9978,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,2003-12-01,"[12, 14, 28]",8.5
9979,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,"[18, 80]",8.5

In [29]:
# get genres details
response1 = requests.get('https://api.themoviedb.org/3/genre/movie/list?api_key=17bd2d67dc3c42c0db9bf2a0c0d85dc6&language=en-US')

In [46]:
response1.json()['genres']

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 80, 'name': 'Crime'},
 {'id': 99, 'name': 'Documentary'},
 {'id': 18, 'name': 'Drama'},
 {'id': 10751, 'name': 'Family'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 36, 'name': 'History'},
 {'id': 27, 'name': 'Horror'},
 {'id': 10402, 'name': 'Music'},
 {'id': 9648, 'name': 'Mystery'},
 {'id': 10749, 'name': 'Romance'},
 {'id': 878, 'name': 'Science Fiction'},
 {'id': 10770, 'name': 'TV Movie'},
 {'id': 53, 'name': 'Thriller'},
 {'id': 10752, 'name': 'War'},
 {'id': 37, 'name': 'Western'}]

In [50]:
genres = dict()
for i in response1.json()['genres']:
  genres[i['id']] = i['name']
genres

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [56]:
all_movies['genres'] = all_movies['genre_ids'].apply(lambda x: [genres[i] for i in x])

In [57]:
all_movies

,title,overview,release_date,genre_ids,vote_average,genres
0,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,"[18, 80]",8.7,"[Drama, Crime]"
1,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,"[18, 80]",8.7,"[Drama, Crime]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,"[18, 80]",8.6,"[Drama, Crime]"
3,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,"[18, 36, 10752]",8.6,"[Drama, History, War]"
4,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-19,"[35, 18, 10749]",8.6,"[Comedy, Drama, Romance]"
...,...,...,...,...,...,...
9975,Gabriel's Inferno: Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,[10749],8.5,[Romance]
9976,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,[37],8.5,[Western]
9977,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,"[35, 18, 10749]",8.5,"[Comedy, Drama, Romance]"
9978,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,2003-12-01,"[12, 14, 28]",8.5,"[Adventure, Fantasy, Action]"
9979,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,"[18, 80]",8.5,"[Drama, Crime]"

**TEXT Preprocessing**

In [61]:
# Now we have the data ready, we can proceed with basic text preprocessing.
# 1. Lowercasing
all_movies['overview'][0].lower()

'spanning the years 1945 to 1955, a chronicle of the fictional italian-american corleone crime family. when organized crime family patriarch, vito corleone barely survives an attempt on his life, his youngest son, michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.'

In [63]:
all_movies['overview'] = all_movies['overview'].str.lower()

In [64]:
all_movies

,title,overview,release_date,genre_ids,vote_average,genres
0,The Godfather,"spanning the years 1945 to 1955, a chronicle o...",1972-03-14,"[18, 80]",8.7,"[Drama, Crime]"
1,The Shawshank Redemption,framed in the 1940s for the double murder of h...,1994-09-23,"[18, 80]",8.7,"[Drama, Crime]"
2,The Godfather Part II,in the continuing saga of the corleone crime f...,1974-12-20,"[18, 80]",8.6,"[Drama, Crime]"
3,Schindler's List,the true story of how businessman oskar schind...,1993-12-15,"[18, 36, 10752]",8.6,"[Drama, History, War]"
4,Dilwale Dulhania Le Jayenge,"raj is a rich, carefree, happy-go-lucky second...",1995-10-19,"[35, 18, 10749]",8.6,"[Comedy, Drama, Romance]"
...,...,...,...,...,...,...
9975,Gabriel's Inferno: Part II,professor gabriel emerson finally learns the t...,2020-07-31,[10749],8.5,[Romance]
9976,"The Good, the Bad and the Ugly",while the civil war rages on between the union...,1966-12-23,[37],8.5,[Western]
9977,Forrest Gump,a man with a low iq has accomplished great thi...,1994-06-23,"[35, 18, 10749]",8.5,"[Comedy, Drama, Romance]"
9978,The Lord of the Rings: The Return of the King,aragorn is revealed as the heir to the ancient...,2003-12-01,"[12, 14, 28]",8.5,"[Adventure, Fantasy, Action]"
9979,GoodFellas,"the true story of henry hill, a half-irish, ha...",1990-09-12,"[18, 80]",8.5,"[Drama, Crime]"

In [70]:
# 2 Remove.Punctuations
import string
exclude = string.punctuation

In [71]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [76]:
all_movies['overview'].str.translate(str.maketrans('','',exclude))[0]

'spanning the years 1945 to 1955 a chronicle of the fictional italianamerican corleone crime family when organized crime family patriarch vito corleone barely survives an attempt on his life his youngest son michael steps in to take care of the wouldbe killers launching a campaign of bloody revenge'

In [77]:
all_movies['overview'][0].lower()

'spanning the years 1945 to 1955, a chronicle of the fictional italian-american corleone crime family. when organized crime family patriarch, vito corleone barely survives an attempt on his life, his youngest son, michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.'

In [78]:
all_movies['overview'] = all_movies['overview'].str.translate(str.maketrans('','',exclude))[0]

In [79]:
all_movies

,title,overview,release_date,genre_ids,vote_average,genres
0,The Godfather,spanning the years 1945 to 1955 a chronicle of...,1972-03-14,"[18, 80]",8.7,"[Drama, Crime]"
1,The Shawshank Redemption,spanning the years 1945 to 1955 a chronicle of...,1994-09-23,"[18, 80]",8.7,"[Drama, Crime]"
2,The Godfather Part II,spanning the years 1945 to 1955 a chronicle of...,1974-12-20,"[18, 80]",8.6,"[Drama, Crime]"
3,Schindler's List,spanning the years 1945 to 1955 a chronicle of...,1993-12-15,"[18, 36, 10752]",8.6,"[Drama, History, War]"
4,Dilwale Dulhania Le Jayenge,spanning the years 1945 to 1955 a chronicle of...,1995-10-19,"[35, 18, 10749]",8.6,"[Comedy, Drama, Romance]"
...,...,...,...,...,...,...
9975,Gabriel's Inferno: Part II,spanning the years 1945 to 1955 a chronicle of...,2020-07-31,[10749],8.5,[Romance]
9976,"The Good, the Bad and the Ugly",spanning the years 1945 to 1955 a chronicle of...,1966-12-23,[37],8.5,[Western]
9977,Forrest Gump,spanning the years 1945 to 1955 a chronicle of...,1994-06-23,"[35, 18, 10749]",8.5,"[Comedy, Drama, Romance]"
9978,The Lord of the Rings: The Return of the King,spanning the years 1945 to 1955 a chronicle of...,2003-12-01,"[12, 14, 28]",8.5,"[Adventure, Fantasy, Action]"
9979,GoodFellas,spanning the years 1945 to 1955 a chronicle of...,1990-09-12,"[18, 80]",8.5,"[Drama, Crime]"